### ISSUE TITLE
was [Wall Wetting AE Link Empty] now forum points to wrong page, we have duplicated page

### ISSUE THREAD

**Issue by moistbrochure** [rusefi/rusefi_documentation#229] opened 2022-07-08 15:05 UTC
As per the request of Sir @duhafnusa4 the wall wetting Ae info page is not there. 
![image](https://user-images.githubusercontent.com/108901504/178013779-29d813cc-abe3-4f5b-907d-0a9f0a79c370.png)
https://github.com/rusefi/rusefi/wiki/wall_wetting

However, we have this page https://github.com/rusefi/rusefi/wiki/X-tau-Wall-Wetting which is full of stuff but not full of the other AE settings/tuning besides the x-tau stuff.

**Comment by duhafnusa4** [comment] 2022-07-08 15:52
Where did you find the link https://github.com/rusefi/rusefi/wiki/wall_wetting ?

**Comment by moistbrochure** [comment] 2022-07-08 16:25
Overview tab
https://github.com/rusefi/rusefi/wiki/overview

**Comment by rusefillc** [comment] 2022-07-08 16:26
https://github.com/rusefi/rusefi/wiki/Overview fixed

**Comment by moistbrochure** [comment] 2022-07-08 16:31
Looks like the "about rusefi" link on the forum takes you to an overview page that has been forgotten about. 
![image](https://user-images.githubusercontent.com/108901504/178032942-a01a6a0d-e4e3-4b21-9865-9167cf4bc169.png)
It takes you to https://github.com/rusefi/rusefi/wiki/Overview which has the link to the wall-wetting page, that is empty. Not the good wall wetting description page. 

The wiki main page https://github.com/rusefi/rusefi/wiki does not include the place to download latest firmware and what not, but it does have the correct wall wetting link.

**Comment by moistbrochure** [comment] 2022-07-08 16:43
Rodger that. New ticket added #230

**Comment by rusefillc** [comment] 2022-07-08 16:44
Now I am getting it, we have two different issues here

#231 which is my duplicate of #230 

and fact that we have two clones of same page

**Comment by rusefillc** [comment] 2022-07-08 16:47
@chuckwagoncomputing do you know anything about https://github.com/rusefi/rusefi/wiki/Overview and https://github.com/rusefi/rusefi/wiki content duplication? I assume we shall wipe out Overview ? replace with link to home?

**Comment by chuckwagoncomputing** [comment] 2022-07-08 16:50
I don't remember anything about it. I say we replace it with a link to home.

**Comment by rusefillc** [comment] 2022-07-08 16:52
Done https://github.com/rusefi/rusefi/wiki/Overview

**Closed by rusefillc** 2022-07-08 16:52 UTC
